# @name createSession
POST http://localhost:3000/api/session
Content-Type: application/json



###

@containerId = {{createSession.response.body.containerId}}


POST http://localhost:3000/api/session/{{containerId}}/exec
Content-Type: text/plain

ls -a ~

###


POST http://localhost:3000/api/session/{{containerId}}/stop

###